import { buildCharFreqMap, strToBytes } from '../crypto'

// buildCharMapFor


function start() {
  const str = `The question of location must of course be decided by the individual taste of the visitor. It would be strange indeed if, with a transient population roughly estimated at 200,000, the city did not possess hotels of all grades and descriptions, from which the most captious-minded person might take his choice and procure satisfaction. Chicago, at the present writing, contains at least 1,500 hotels, with constant additions each year. There is no more difficult task than to tell a man with any accuracy what hotel will suit him best. A caravansary that would delight one man would disgust another and vice versa. The most satisfactory plan, therefore, and the safest, is to give a brief pen-sketch of the leading hotels, with some idea of the special characteristics of each and the style of entertainment they afford.
The Lake Front hotels—the Richelieu, Auditorium, and Leland—enjoy the cream of the new25 transient patronage. By “new,” is meant those people who have never before visited Chicago, and who naturally select the houses with the prettiest sites. The Auditorium (Michigan Avenue and Congress Street), despite its gorgeousness and the flourish of trumpets with which it was opened, does not indulge in ruinous rates. It is a very large hotel and accommodations may be had therein from $4 per day up. Perhaps it is this moderate charge that makes it so great a favorite with the theatrical profession, the more prosperous members of which enjoy the comfort it affords. Well-to-do managers, famous stars, and sometimes interrogatively opulent soubrettes and chorus girls seek lodging at the Auditorium, and some very pretty romances are narrated of flirtations more or less interesting which the “blooded” habitues of this swell hotel “strike up” with the fair footlight favorites who enjoy its hospitality. It is worth the price of a day's board, or at least a dinner, sometimes, to take a stroll in the corridors and catch the fragments of delicious lays that are being caroled forth by the song birds who are practicing their chosen art in the sanctity of their various chambers. Especially is this the case during a season of grand or light opera in the great theater adjoining the hotel, in which case the latter is sure to be thronged with singers of both sexes, and of all grades of artistic and professional prominence.26 There is a roomy balcony over the entrance to the Auditorium which, on pleasant days, is thronged with gaily dressed people of both sexes, who sit there and enjoy the dual delight of drinking in the balmy air and watching the cavalcade on the broad avenue below.

A block north of the Auditorium is the Richelieu, the famous hostelry the destinies of which are presided over by the renowned “Cardinal” Bemis. For people of means, to whom money is less of an object than the engagement of luxuries, the Richelieu, they say, is the place par excellence at which to stop. Some notable people have honored the Richelieu with their presence, and one is just as liable to run plumb against a real, live English Lord or Italian Marquis within its doors as against a plain, everyday American citizen. Sara Bernhardt selects the Richelieu when in the city; so does Mrs. Langtry when the confines of her private car become too narrow for comfort. The Richelieu is famous for the rare pictures that adorn its walls, some of which are worth small fortunes, and also—whisper this with bated breath, Oh, ye irreverent!—for its wine cellars, which are stocked with some of the rarest and costliest vintages to be found on the entire continent. On state occasions, when the Cardinal is entertaining some choice party of notables, he is wont to disappear suddenly, absent himself for about fifteen minutes and then27 reappear with a quaint-shaped bottle or two in either hand covered with cobwebs. Those who sample the contents of said bottles close their eyes,28 pat their stomachs softly as the divine liquid glides down their throats, and then shed tears of joy and gratitude to the Cardinal for having given them the happiest moment of their lives. If you are a connoisseur of wines and wish to test your art in judgment thereof, cultivate the acquaintance of the Cardinal, and perhaps he will go down into the cellar for you.

Mr. Warren Leland, who recently sold the hotel of that name, always said he had the prettiest house in Chicago, and there are some people who agree with him. The Leland rates, on the American plan, are from $3 to $5 per day up; the European, $1.50 up. The Leland is known as the “home hotel” of Chicago, and there is a tradition abroad to the effect that people who once patronize it never go elsewhere.

“The Blooded District”—Before proceeding to the consideration of other prominent hotels, it may be interesting to inform the reader that the district which we are about to leave, and of which the three hostelries enumerated form the nucleus, has achieved some fame in the annals of the town as “the blooded district”—so-called for the reason that the “high-rolling” young men of the city have made it a sort of headquarters or rendezvous, both before and after the hours when sober-minded and steady-going folk are fast asleep. The Auditorium, Richelieu, and Leland Cafes, together with29 Devine's wine-room on the other side of Jackson Street, and Colonel John Harvey's “Wayside Inn” in the alley, form a sort of circuit or beat, which these “rapid” young men (i.e. the “bloods”) travel at all times, including such hours as the sale of cheering beverages is forbidden by city ordinance. Of these, Harvey's is perhaps the most unique resort, though if one cannot find his friends in one of the places named after midnight he is tolerably certain to encounter them in one of the others. Colonel Harvey is the father of the pert little soubrette, Hattie Harvey, of whom the great diva, Patti, became so desperately enamored as to invite her to her castle in Wales, and admirers of the young lady are fond of dropping in to discuss her merits with her papa, the Colonel, who, it goes without saying, is the most devoted of her admirers. If you praise Hattie's beauty to the Colonel he will mix for you, with his own hands, one of his choicest drinks; if you swear on your honor that she is destined to become the greatest actress of the century, he will probably crack a bottle. The door of Harvey's “Wayside Inn” is tightly closed at midnight, but the initiated may gain ready admittance by learning the pass-word of the night and roaring it, in tones more or less musical, through the key-hole. You can always tell whether there is any fun going on in Harvey's by the galaxy of hackmen who stand in line at the curb, waiting for the30 “boys” to emerge in the small hours of the morning. But we may now leave the “blooded district” and take a glance at other South side hotels.

The venerable Palmer House stands like a bulwark at the corner of State and Monroe Streets, its vast expanse stretching away for half a block. The Palmer enjoys a steady patronage from people who have been “putting up” there for years. It has a large clientele of the better class of commercial travelers. The wits of the town crack jokes at the expense of the Palmer on the score of the number of guests of Hebraic extraction it shelters. Be that as it may, the Palmer welcomes all who pay their bills and those who patronize it generally possess that admirable qualification. The Palmer's rates are $3 to $5 per day.
There is a little room on the sixth floor of the Palmer which is an environ of romantic interest,31 it having been the scene of one of the most famous tragedies in Chicago's history. In the summer of 1882, it was occupied by Charles Stiles, the popular and high-living “caller” of the Board of Trade. Early one morning a veiled woman, whose tasteful but somber raiment revealed the outlines of an entrancing figure, took the elevator to the sixth floor and knocked at the door of Stiles' room. He came out scantily clad in response to the summons. There was a flash, the ringing report of a revolver, and in another instant the young man lay dead on the floor. The woman knelt down, kissed his forehead and submitted to arrest without a murmur. She was an Italian, Teresa Sturlata by name, and the mistress of Stiles. His previous abuse of her, as testified to at the trial, so influenced the jury in her behalf that she received but the nominal punishment of one year in the penitentiary, though her great beauty doubtless had some influence on the leniency of the sentence. Many men went daft over the beautiful murderess. Some of the letters that she received while in jail were published, and precious epistles they were, too. They all contained protestations of affection, and several offers of marriage were included among them. The woman went to the penitentiary and served her sentence. When released she disappeared as completely as though the earth had swallowed her. Her present32 whereabouts is unknown, but the room made famous by the great tragedy is still pointed out to new guests at the Palmer.

The Grand Pacific, on South Clark Street, kept by Landlord Drake, is of the same class as the Palmer, enjoying a steady patronage all the year round. The rates are $3 to $5 per day. The Tremont, kept by Mr. Eden (Lake and Dearborn) and the Sherman, kept by Mr. Pierce (Clark and Randolph), are of the same grade as the Palmer and Grand Pacific.

These comprise the list of first-class down-town hotels, though several others are in progress of construction, with a view to caring for the thousands of strangers who will visit the World's Fair. Notable among these is the Great Northern, which, under the supervision of Mr. Eden, has just been pushed to completion. It is on Dearborn Street opposite the post office, between Jackson and Quincy, being situated, therefore, in the very heart of the business district.

The Victoria, the new hotel on the site of the building formerly known as the Beaurivage, Michigan Avenue and Congress Street, is a fashionable house, patronized by the best people. The same is true of The Wellington, corner of Jackson Street and Wabash Avenue.

The smaller hotels are much too numerous to particularize. They are scattered in all directions33 and their rates for rooms vary from fifty cents upward per day. There is no street in the business part of the city without two or three such hotels, and the traveler must be hard to please who cannot suit himself at one or another among so many. The residence part of the city, particularly on the North and South sides, is thickly dotted with first-class family hotels, where persons contemplating an extended stay may obtain quiet accommodation in the exact ratio for which they care to pay. The two most magnificent family hotels are the Virginia, 78 Rush Street, and the Metropole, Michigan Avenue and Twenty-third Street. These two houses cannot be surpassed for style and elegance and they are patronized exclusively by people of means.

The Wayfarer having received some hints as to the quarters in which he may establish himself, one reaches the much more important question of how he shall amuse or divert himself while here. Before coming to the point of the more unique or unusual modes of diversion with which the city abounds one's first thoughts naturally turn to the theaters.

Chicago is famous as a theatrical center, and the very best attractions are constantly to be found at one or another of the great play-houses. Just at this stage, therefore, it is meet to utter a few remarks on the leading theaters and the class of excellent entertainment they present to their patrons.

The Chicago Opera House.—This theater, one of the youngest in Chicago, is perhaps entitled to primary mention by reason of its virtual35 monopoly, except at stated intervals of the cream of the city's theatrical business. It has a very large seating capacity; was first opened about seven years ago with the tragedian, Thomas Keene, as the attraction. The director of the Chicago Opera House, Mr. David Henderson, has achieved a wide popularity, both in and out of the profession, and is aided in his efforts by a corps of efficient assistants, notable among who are Messrs. Thomas W. Prior and Max Godenrath. While presenting to the public attention first-class attractions all the year around, the Chicago Opera House has earned the major part of its distinction by the superb extravaganzas it has been producing annually. These extravaganzas usually commence in May and run through the summer months, thus securing to the house a steady patronage during the “dog-days.” It is beyond all question that the first of these spectacles, the “Arabian Nights,” established Mr. Henderson's reputation as a purveyor of this class of entertainment, (termed by the irreverent “leg shows.”) The second production, the “Crystal Slipper,” enhanced this reputation, and those succeeding—“Bluebeard Jr.” and “Sinbad”—kept it going. This year (1892) the summer spectacle at The Chicago will be “Ali Baba, or the Forty Thieves,” and if advance gossip is to be taken as evidence, it will transcend in magnificence anything of its kind that has ever been produced under36 Mr. Henderson's supervision. The libretto of “Ali Baba” is by Harry B. Smith, the distinguished wit and literateur, who has performed a like service for the pieces before mentioned. The Chicago Opera House is situated on the South side of Washington Street, between Clark and La Salle Streets, and is invariably thronged throughout the hot weather. Mr Henderson manages to group upon his stage as choice a galaxy of feminine loveliness as is to be found in any climate, and the costuming (or rather the lack of it) is doubtless as gratifying to the performers as it is to the spectators, being constructed on the hot weather plan; light and airy. It is no uncommon sight to see a party of honest country folks appearing, gripsacks in hand at the doors of the Chicago Opera House, having come straight from the train to the theater to witness the show, the fame of which had penetrated to their homes in the country; and which, after their return, they would rather die than let their families and the church folks know they had seen.

McVicker's Theater.—It is situated on the south side of Madison Street, between State and Dearborn, and is one of the oldest resorts of its kind in the city, though the present structure is quite new, having been reconstructed on the site of the old one, which was destroyed by fire in the spring of 1891. The attractions at McVicker's37 are usually of the solid, legitimate order, though the gray-haired proprietor occasionally is guilty of a lapse to a variety show. McVicker's, however, is the home of high-class drama and comedy, and the theater itself is perhaps without a rival on the continent in the way of magnificent decorations and comfortable furnishing. While Mr. McVicker is opposed to Sunday performances, he occasionally permits them, which enables the stranger, not infrequently, to encounter a first-class Sunday night show within a few paces of his hotel.

The Grand Opera House.—This admirable play-house is located on the east side of Clark Street, just north of Washington. It is another old-established theater enjoying a large patronage. The Grand is the home of Hoyt's farces, each of these fanciful productions having been produced successfully at Mr. Hamlin's temple. At the Grand, also appear most of the German companies, though the latter will, it is to be presumed, go to the new edifice, Schiller theater, Randolph Street, near Dearborn.

Hooley's Theater.—Located conveniently on Randolph, between Clark and La Salle Streets, is devoted to all sorts of attractions, and is one of the handsomest theaters of its size in the country. The patrons of Hooley's may run the gamut from low comedy to grand opera; and Irish comedy-drama38 often following immediately after one of the high-class engagements, such as that of the Madison Square or Lyceum Theater Companies.

Columbia Theater.—In the very heart of the business district, on the south side of Monroe, between Dearborn and Clark Streets. This theater is one of the oldest in the city, and has passed through many managements, being at present under the direction of the Hayman Bros, and Mr. Will J. Davis, both of whom are gentlemen of the highest standing in the profession and thoroughly competent to cater to the desires of an amusement-loving public. The attractions presented at the Columbia are of a wide range, the properties of the house39 being suited to the production of grand or light opera more than anything else. Some of the first artists in the world have appeared at the Columbia, notably, Henry Irving and Ellen Terry, the latter having, on one memorable night, formally christened the theater which, prior to that time, was known as Haverley's; Sara Bernhardt, Adelina Patti, Christine Nielsson, and others almost equally famous. The seating capacity of the Columbia is as large as that of any of the down-town theaters and it possesses the advantage of large, comfortable seats, very liberally spaced, that other managers might do well to emulate.

The “Provincial” Theaters.—The houses mentioned are known as the “down-town” or high-priced theaters, the scale of prices ranging from 25 cents to $1.50 per seat. In addition to these, however, there are a number of houses, some of which are equally large, scattered about in the three sections of the city, which are known as the “second class” or “provincial” theaters, where the price of admission ranges from 15 cents to $1.00. Of these may be mentioned the following: South Side—Alhambra, State and Archer Ave.; Madison Street Opera House, 83 Madison Street; Olympic, 46 South Clark Street; Havlin's, Wabash and 19th Street; People's, 339 State Street. North Side.—Clark Street Theater, Clark and40 Kinzie Streets; Criterion, 374 Sedgwick Street; Windsor, 459 North Clark Street. West Side.—Haymarket, 169 West Madison Street; Lyceum, 58 South Desplaines Street; Standard, 167 South Halsted Street; Halsted Street Theater, Halsted and West Congress Streets.

The outside, or provincial theaters usually offer a more sensational type of plays, specimens of the wild and woolly border drama being usually presented for the edification of their mercurial patrons. The Park Theater, 335 State Street, ought not to rank with the other theaters, but is often patronized by travelers whose tastes lead them to desire entertainment of the more democratic type. The accessories of tobacco smoke and liquid refreshment, which are to be indulged in at the Park, form an attraction that they find it impossible to resist, nor is it difficult for a patron, whose pocketbook enables him to indulge in such luxuries, to obtain an introduction through the influence of the manager to the more or less fascinating “fairies,” who go through their performances on the stage. Further mention of the Park will be made later.

Detailed mention of the magnificent opera house in the Auditorium building has been reserved until now in order that it might take its proper place in the description of the mighty edifice which is the wonder and admiration of the United States, and a topic of comment to some extent in Europe.

The project of the Auditorium, three sides of which face Wabash Avenue, Congress Street and Michigan Avenue, is said to have emanated from the brain of Mr. Ferd W. Peck, a capitalist, who, in a speech to the Commercial Club, outlined the advantages that would be likely to accrue to the city from the possession of such a building. As the Auditorium is one of the sights of the city, it deserves a special description.

The Auditorium Hotel, mention of which has been made in a previous chapter, fronts on Michigan Avenue and occupies the upper floor of the44 building, the colossal outlines and massive architecture of which, rivaling as they do the ancient Coliseum of Rome, strike the beholder dumb with admiration. The stock company that constructed the Auditorium was formed at Mr. Peck's suggestion in the spring of 1886, and in January of the following year work was commenced upon it. Less than eighteen months afterward the building had progressed to a stage that made it possible to hold the National Convention of 1888 under the roof of the great theater. On that occasion 12,000 people cheered the nomination of Harrison as the presidential candidate. The formal dedication of the great structure took place December 9, 1889. The star of the occasion was Adelina Patti, the world-famous singer, who, although she had dyed her hair a brilliant red, aroused a cyclone of enthusiasm by her time-honored rendition of “Home, Sweet Home.” Speeches were made by Benjamin Harrison, President of the United States; by DeWitt C. Cregier, then Mayor of Chicago; by Ferd W. Peck, President of the Auditorium Company, and others. It required an expenditure of nearly $2,000,000 in hard cash to erect the Auditorium, and the men who invested their money in the project are drawing a fair interest on the amount of their wise venture. The building has a frontage of 187 feet on Michigan Avenue, 361 feet on Congress Street, and 161 feet on Wabash Avenue.45 The material used is mostly American granite from Maine and Minnesota; the ornamentation being largely in Mexican onyx. To the visitor who stands rapt in admiration at the sight of this superb edifice, a few figures may not be uninteresting. The main building is 144 feet in height; the tower on the Congress Street side, 225 feet, with lateral dimensions of 40 x 71 feet. The building weighs in its entirety 110,000 tons. There are 17,000,000 brick in the building and 50,000,000 pieces of marble. The flooring is in Antique Mosaic.

Now for the theater itself, which is, after all, the main interior attraction of the Auditorium, the smaller halls and office suites which are contained in the main structure possessing only a commercial interest. The theater has a regular seating capacity of 4,000, though when it is arranged for a convention or a ball it will hold three times that number. The stage is ninety-eight feet in width and 6,862 square feet in area. The great lobby with its massive pillars and porticos, prepares the visitor for the sublime magnificence of the immense audience chamber. The ceiling, which is decorated in white and gold, glitters with a myriad of electric lamps and the spectacular effect, when the house is filled with a fashionable audience, the long tiers of boxes gleaming with the brilliant costumes and jewels of scores of handsome women,46 surpasses description. It must be seen to be appreciated. The Auditorium theater is equipped, among other things, with an organ that is said to be the finest and most complete in the world, possessing as it does, 7,193 pipes.

But without question the tower is a stupendous feature of the Auditorium and is most popular with strangers; it may be said that no stranger should leave the city without visiting it. Enter from the Congress Street side and purchase a ticket at the box office, costing twenty-five cents. The elevator carries you up at rapid speed to the top. The final ascent is made by a small flight of iron stairs and the tower is reached. The splendor of the view from this tower can be imagined but not described. On a clear day the Michigan shore is discernible far away over the blue water of the lake, while on the east side, north and south the eye may penetrate to the furthest limits of the city. To stand there and look down on the mazes of buildings and the swarming thousands of your fellowmen produces a strange feeling of awe and wonderment. The popularity of the tower with sight-seers may be imagined from the fact that the attendance brings in an average of $120 per day to the company throughout the year.

Preparations are now in progress for the presentation at the Auditorium during the World's Fair year of a theatrical spectacle which shall47 eclipse anything of the kind ever before seen in any country. The plans are yet in embryo, but a rough outline has been drawn. The production, which is to be historical in character, will be under the direction of Managers Adams, Abbey and Grau. It will open in the spring of 1893, and run through the World's Fair season.

The New German Theater on Randolph Street, between Dearborn and Clark, deserves special mention by reason of the fact that it will be the youngest of all Chicago first-class theaters, and because great promises have been made as to the magnificence of its furnishings and equipment. The structure is fire-proof, nine stories in height with a large square tower fifteen feet in height surmounted by a cupola. The main building fronts eighty-four feet on Randolph Street with a depth of 186½ feet. There will be a covered balcony in front from which street parades may be advantageously viewed. The cornices, balustrades and other parts of the building are decorated with rich carvings. The construction is of steel columns and cross-beams, the outer walls being in terra cotta. The main entrance leading to the theater is thirty-two feet wide. All the floors and wainscoting are in polished marble. From the entrance to the theater foyer will extend two vestibules, in the inner one of which the box office is located. Four passenger elevators furnish access to the48 hotel and club rooms of which the main portion of the palatial structure will consist. Broad marble stairs lead from the foyer to the main floor, balcony and gallery of the theater, the Auditorium plan of seating the people having been decided upon. The theater will seat 1,300 people. The stage has a superficial area of 3,200 square feet, with a proscenium arch twenty-nine feet wide and thirty feet high.

Seven stories of the building are devoted to the hotel, which also deserves a word of description. There are 131 guest chambers, 39 bath rooms, a dining room 76 feet long by 49 wide, and other features. The hotel will of course have a separate entrance. Club, billiard, card, and other rooms occupy the tenth floor. The eleventh is devoted to a fine ball-room, separate quarters being provided for the servants on the floors above.

The total cost of this fine structure is estimated at $600,000, inclusive of the price paid for the ground. The building is erected by a company of which the following well-known citizens are directors: A. C. Hesing, Theodore Arnold, Louis Wolff, Edward Eiblein, Franz Amberg, Charles Wacker, C. P. Dose, Louis Wampold, J. A. Orb, Joseph Scheurer, William Heineman, George E. Weiss, John M. Krause, C. Herman Plautz, and Theodore Oehne.

It goes without saying that this will be an attractive place for strangers to visit.`
  const bytes = strToBytes(str)

  const char_map = buildCharFreqMap(bytes)
  console.log(char_map)
}

start()
